# TRABALHO FEITO POR DANIEL, INÊS E RAFAEL

from time import sleep

print(" --- SEJA BEM VINDO À COMPANHIA IEFP ---")
sleep(0.5)
print("Para dar seguimento ao processo de adesão. por favor registe uma conta:\n")
sleep(0.5)
print("Insira o username.")
name_user = input("Username: ").strip()
print()
print("Insira o email.")
email_user = input("Email: ").strip()
test1_email = email_user.find("@")
test2_email = email_user.find(".")
if (test1_email == -1 or test2_email == -1):
    print()
    print("Email invalido, por favor insira denovo:")
    email_user = input("Email: ").strip()
    print("Email válido!")
    print()
else:
    print("Email válido!")
    print()
print("Insira a password.")
passw_user = input("Password: ")
passwv_user = input("Repita a password: ")
passwtest_user = passw_user.find(" ")
if (passw_user != passwv_user or passwtest_user != -1):
    print("Password invalida.")
    print()
    passw_user = input("Password: ")
    passwv_user = input("Repita a password: ")
    print("Password válida!")
    print()
else:
    print("Password válida!")
    print()
print("Registando conta", end=".")
sleep(0.5)
print(end=".")
sleep(0.5)
print(end=".")
print()
print()
sleep(1)
print("Conta registada com sucesso.\n\n Bem vindo á familia IEFP!")
print()
sleep(1)
print("-_-_- Companhia IEFP -_-_-\n")
print("[ 1 ] - Login")
print("[ 2 ] - Sair\n")
opcao = int(input("Escolha o que deseja fazer a seguir:\n --> "))
sleep(0.5)
print()
if (opcao == 1):
    print("Insira o seu username.")
    username_log = input("Username: ")
    print()
    print("Insira a sua password.")
    passwv_user = input("Password: ")
    sleep(0.5)
    print()
    if (username_log == name_user and passwv_user == passw_user):
        print("Login realizado com sucesso.")
    if (username_log != name_user or passwv_user != passw_user):
        print("Username ou password invalidos!")
        print("Por favor realize o login mais uma vez!")
        print()
        sleep(0.5)
        print("Insira o seu username.")
        username_log = input("Username: ")
        print()
        print("Insira a sua password.")
        passwv_user = input("Password: ")
        sleep(0.5)
        if (username_log != name_user or passwv_user != passw_user):
            print("Estas bloqueado de aceder à companhia!")
        print()
        print("Login realizado com sucesso!")
elif (opcao == 2):
    print("Saindo do programa", end=".")
    sleep(0.5)
    print(end=".")
    sleep(0.5)
    print(end=".")
else:
    print("Opção Inválida!")
    print("Saindo do programa", end=".")
    sleep(0.5)
    print(end=".")
    sleep(0.5)
    print(end=".")
